export enum speakersTypes {
  SPEAKERS_SELECT_DATA = 'SPEAKERS_SELECT_DATA',
  FETCH_SPEAKERS_REQUEST = 'FETCH_SPEAKERS_REQUEST',
  FETCH_SPEAKERS_SUCCESS = 'FETCH_SPEAKERS_SUCCESS',
  FETCH_SPEAKERS_FAILURE = 'FETCH_SPEAKERS_FAILURE',
}
